#!/bin/bash

# moving this to either boostrap on migrations workflow
set -e

echo "Running Postgres initialization script..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
--------------------
-- Sensor app setup
--------------------
CREATE ROLE $SENSOR_SVC_USER WITH LOGIN PASSWORD '$SENSOR_SVC_PASSWORD';
\connect sensors;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $SENSOR_SVC_USER;

GRANT ALL PRIVILEGES ON SCHEMA app TO $SENSOR_SVC_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA app TO $SENSOR_SVC_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA app TO $SENSOR_SVC_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $SENSOR_SVC_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO $SENSOR_SVC_USER;

EOSQL

echo "Success - Ran Setup Script"